version: "3.8"

services:
  scraper_api:
    build: .
    container_name: scraper_api
    networks:
      - argos-net
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    mem_limit: 1g
    memswap_limit: 1g
    cpus: "1.0"

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    networks:
      - argos-net
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_data/.n8n-files:/home/node/.n8n-files
      - .:/app
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_USER_FOLDER=/home/node/.n8n
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_BLOCK_FS_WRITE_ACCESS=false
    restart: always
    mem_limit: 512m
    memswap_limit: 512m
    cpus: "0.5"

networks:
  argos-net:
    driver: bridge
